"""Commit34 frozen-committee replay. Never optimizes parameters on OOS.

CLI: python backtest_commit34.py --ohlcv DIR --committee-levels FILE.csv --out DIR

Committee levels must be generated by running the EXACT canonical Commit33.4.x
Entry/SL/TP pipeline causally, with timestamps and audit fields. OHLC alone is
insufficient to claim profitability compatible with this system; this runner
therefore rejects synthetic/heuristic levels and creates explicit NO_DATA rows.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
from collections import defaultdict
from datetime import timedelta
from pathlib import Path

import pandas as pd

from commit34_family_engine import FAMILIES, discover_families
from futures_universe import RISK_CLASS_SYMBOLS, RISK_CLASS_TIMEFRAMES

# Read the official MultiAsset universe without importing its Gunicorn/Futures
# graph.  Backtests must run OFFLINE without starting the application/threads.
def _multiasset_universe():
    import ast
    module=ast.parse(Path(__file__).with_name('multiasset_system.py').read_text(encoding='utf-8'))
    found={}
    for node in module.body:
        if isinstance(node,ast.Assign):
            for target in node.targets:
                if isinstance(target,ast.Name) and target.id in ('MULTIASSET_SYMBOLS','MULTIASSET_TIMEFRAMES'):
                    found[target.id]=ast.literal_eval(node.value)
    return found['MULTIASSET_SYMBOLS'], found['MULTIASSET_TIMEFRAMES']

MULTIASSET_SYMBOLS, MULTIASSET_TIMEFRAMES = _multiasset_universe()

TF_SECONDS={'30m':1800,'1h':3600,'2h':7200,'4h':14400,'12h':43200,'1D':86400}
EXPECTED_FIELDS=('symbol','timeframe','candle_open','action','family','entry','stop_loss',
                 'take_profit','created_at','geometry_source','signal_status')


def universe():
    for group,syms in RISK_CLASS_SYMBOLS.items():
        for sym in syms:
            for tf in RISK_CLASS_TIMEFRAMES[group]:
                for family in FAMILIES:
                    yield (group,sym,tf,family)
    for sym,meta in MULTIASSET_SYMBOLS.items():
        for tf in MULTIASSET_TIMEFRAMES:
            for family in FAMILIES:
                yield (meta['asset_class'],sym,tf,family)


def metrics(xs):
    n=len(xs)
    if not n: return {'n':0,'expectancy_r':None,'net_r':None,'pf':None,'max_dd_r':None,'win_rate':None}
    profit=sum(x for x in xs if x>0); loss=-sum(x for x in xs if x<0)
    balance=peak=dd=0.0
    for x in xs:
        balance+=x;peak=max(peak,balance);dd=max(dd,peak-balance)
    return {'n':n,'expectancy_r':round(sum(xs)/n,5),'net_r':round(sum(xs),5),
            'pf':round(profit/loss,5) if loss>0 else None,'max_dd_r':round(dd,5),
            'win_rate':round(100*sum(x>0 for x in xs)/n,2)}


def resolve_trade(frame, i, row, *, cost_bps=12.0, max_wait=3, hold_bars=16):
    """Next-candle limit order with bid/ask round-trip proxy and pessimistic SL.

    0 is candle at which the signal was established.  Only bars i+1 onward
    can trigger entry.  Neither future high/low nor next open changes entry.
    """
    action=row['action']; side=1 if action=='LONG' else -1
    ent=float(row['entry']);sl=float(row['stop_loss']);tp=float(row['take_profit'])
    if not (math.isfinite(ent) and math.isfinite(sl) and math.isfinite(tp)
            and ((sl<ent<tp) if side>0 else (tp<ent<sl))):
        return None,'INVALID_GEOMETRY'
    risk=abs(ent-sl)
    if risk<=0:return None,'INVALID_RISK'
    entry_i=None
    for j in range(i+1,min(len(frame),i+1+max_wait)):
        if float(frame.low.iloc[j])<=ent<=float(frame.high.iloc[j]):
            entry_i=j;break
    if entry_i is None: return None,'ENTRY_NOT_TOUCHED'
    cost_r=cost_bps/10000*ent/risk
    for j in range(entry_i,min(len(frame),entry_i+hold_bars)):
        hi=float(frame.high.iloc[j]);lo=float(frame.low.iloc[j])
        stop=(lo<=sl if side>0 else hi>=sl)
        target=(hi>=tp if side>0 else lo<=tp)
        if stop: return round(-1.0-cost_r,6),'SL_OR_DOUBLE_TOUCH'
        if target: return round(abs(tp-ent)/risk-cost_r,6),'TP'
    j=min(len(frame)-1,entry_i+hold_bars-1)
    # Censored exit at horizon, no invented TP.
    return round(side*(float(frame.close.iloc[j])-ent)/risk-cost_r,6),'TIME_EXIT'


def load_levels(path):
    if not path or not path.exists(): return {}, 'NO_COMMITTEE_GEOMETRY_EXPORT'
    with path.open('r',encoding='utf-8-sig',newline='') as fh:
        reader=csv.DictReader(fh)
        if not set(EXPECTED_FIELDS).issubset(reader.fieldnames or ()):
            return {},'MISSING_REQUIRED_COMMITTEE_COLUMNS'
        out={}
        for r in reader:
            if r['geometry_source']!='EXACT_CANONICAL_COMMITTEE_REPLAY':continue
            if r['signal_status']!='EXECUTABLE_SIGNAL':continue
            stamp=pd.to_datetime(r['candle_open'],utc=True,errors='coerce')
            created=pd.to_datetime(r['created_at'],utc=True,errors='coerce')
            if pd.isna(stamp) or pd.isna(created) or created<stamp:continue
            tf_seconds=TF_SECONDS.get(r['timeframe'])
            if not tf_seconds:continue
            # A causal replay cannot retrofit a committee decision generated
            # many bars AFTER the alleged source candle.
            if (created-stamp).total_seconds() > tf_seconds+300:continue
            key=(r['symbol'].upper(),r['timeframe'],stamp,r['action'].upper(),r['family'])
            out[key]=r
        return out,'OK'


def frame_for(folder,symbol,tf):
    if not folder:return None
    for name in (f'{symbol}__{tf}.csv',f'{symbol.replace("-", "_")}__{tf}.csv'):
        path=folder/name
        if not path.exists():continue
        try:
            df=pd.read_csv(path)
            if 'time' in df and 'timestamp' not in df:df=df.rename(columns={'time':'timestamp'})
            if not {'timestamp','open','high','low','close','volume'}.issubset(df.columns):continue
            df['timestamp']=pd.to_datetime(df.timestamp,utc=True,errors='coerce')
            for c in ('open','high','low','close','volume'):
                df[c]=pd.to_numeric(df[c],errors='coerce')
            df=df.dropna().sort_values('timestamp').drop_duplicates('timestamp').reset_index(drop=True)
            if len(df)<240:return None
            delta=df.timestamp.diff().dt.total_seconds()
            # Require exact native TF, no 30m resampling into 1D when sessions
            # might create look-ahead or partial candles.
            if (delta.iloc[1:]<TF_SECONDS[tf]).any():return None
            return df
        except (ValueError,OSError,KeyError):pass
    return None


def replay(ohlcv_dir=None,committee_levels=None,out_dir=None,*,cost_bps=12.0):
    folder=Path(ohlcv_dir) if ohlcv_dir else None
    levels,lstatus=load_levels(Path(committee_levels) if committee_levels else None)
    by_cell={};rows=[];verified=0
    for group,symbol,tf,family in universe():
        cache_key=(symbol,tf)
        if cache_key not in by_cell:by_cell[cache_key]=frame_for(folder,symbol,tf)
        df=by_cell[cache_key]
        item={'group':group,'symbol':symbol,'timeframe':tf,'family':family,
              'is':metrics([]),'selection':metrics([]),'oos':metrics([]),
              'status':'NO_OHLCV' if df is None else lstatus,
              'live_eligible':False,'geometry_source':'EXACT_CANONICAL_COMMITTEE_REPLAY_REQUIRED'}
        if df is not None and levels:
            split_a=int(.60*len(df));split_b=int(.80*len(df))
            splits=[[],[],[]];matches=0
            # Fixed features/calibration.  Never change entry/SL/TP or score to
            # force profitability.  Last complete bar known at each decision.
            for i in range(56,len(df)-17):
                if i>0 and (df.timestamp.iloc[i+1]-df.timestamp.iloc[i]).total_seconds()<TF_SECONDS[tf]:continue
                row=discover_families(df.iloc[:i+1],timeframe=tf,
                    market='multiasset' if group not in RISK_CLASS_SYMBOLS else 'futures',
                    asset_class=group)
                for candidate in row.get('candidates') or []:
                    if candidate['family']!=family:continue
                    side=candidate['action']
                    key=(symbol.upper(),tf,df.timestamp.iloc[i],side,family)
                    entry_row=levels.get(key)
                    if entry_row is None:continue
                    result,status=resolve_trade(df,i,entry_row,cost_bps=cost_bps)
                    if result is None:continue
                    matches+=1
                    split=0 if i<split_a else 1 if i<split_b else 2
                    # Keep decisions in the correct split; do not allow trade
                    # outcomes to cross into a future holdout window.
                    stop=min(split_a,split_b) if split==0 else split_b if split==1 else len(df)
                    if i+3+16>stop:continue
                    splits[split].append(result)
            item.update({'is':metrics(splits[0]),'selection':metrics(splits[1]),
                         'oos':metrics(splits[2]),'matched_committee_signals':matches})
            item['status']='TESTED' if any(splits) else 'NO_MATCHING_CAUSAL_COMMITTEE_LEVELS'
            if all(len(xs)>=minimum and metrics(xs)['expectancy_r']>0 for xs,minimum in zip(splits,(35,12,12))):
                # OOS alone is not enough: separate walk-forward + strict route
                # alignment and review are required before live promotion.
                if item['oos']['pf'] is not None and item['oos']['pf']>=1.10:
                    item['status']='CANDIDATE_REQUIRES_WALK_FORWARD'
                    verified+=1
        rows.append(item)
    report={'version':'COMMIT34_CAUSAL_REPLAY_V1','source':'REAL_OHLCV_AND_EXACT_COMMITTEE_RECORDS_ONLY',
            'family_count':len(FAMILIES),'combinations':len(rows),
            'status':'RESEARCH_INCOMPLETE' if not verified else 'CANDIDATES_REQUIRE_WALK_FORWARD',
            'oos_selection_tuned':False,'parameter_search_performed':False,
            'cost_bps_round_trip':cost_bps, 'rows':rows}
    if out_dir:
        dest=Path(out_dir);dest.mkdir(parents=True,exist_ok=True)
        (dest/'COMMIT34_IS_OOS.json').write_text(json.dumps(report,indent=2,ensure_ascii=False),encoding='utf-8')
        with (dest/'COMMIT34_MATRIX.csv').open('w',encoding='utf-8',newline='') as fh:
            w=csv.writer(fh);w.writerow(['group','symbol','timeframe','family','status','IS_n','IS_E','SEL_n','SEL_E','OOS_n','OOS_E','OOS_PF','live_eligible'])
            for row in rows:
                w.writerow([row[k] for k in ('group','symbol','timeframe','family','status')]+[row['is'][k] for k in ('n','expectancy_r')]+[row['selection'][k] for k in ('n','expectancy_r')]+[row['oos'][k] for k in ('n','expectancy_r','pf')]+[row['live_eligible']])
    return report


if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--ohlcv');parser.add_argument('--committee-levels');parser.add_argument('--out',default='commit34_backtest_output');parser.add_argument('--cost-bps',type=float,default=12.0)
    args=parser.parse_args(); report=replay(args.ohlcv,args.committee_levels,args.out,cost_bps=args.cost_bps)
    print(json.dumps({k:v for k,v in report.items() if k!='rows'},indent=2))
